# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(upload_to='tracks/songs'),
        ),
    ]
