# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='albums/covers'),
        ),
    ]
